name: CI/CD Pipeline

on: push

permissions:
  contents: read
  pull-requests: read

env:
  CI_OTP_VERSION: "25.2"
  CI_GLEAM_VERSION: 1.1.0
  CI_ELIXIR_VERSION: "1.14"
  CI_REBAR3_VERSION: "3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up BEAM dependencies
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          gleam-version: ${{ env.CI_GLEAM_VERSION }}
          elixir-version: ${{ env.CI_ELIXIR_VERSION }}
          rebar3-version: ${{ env.CI_REBAR3_VERSION }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.43.5
      - name: Install npm and Gleam package dependencies
        run: npm ci && gleam deps download
      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlintrc.json
      - name: Check formatting
        run: npm run check
      - name: Run tests
        run: npm run test
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up BEAM dependencies
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          gleam-version: ${{ env.CI_GLEAM_VERSION }}
          elixir-version: ${{ env.CI_ELIXIR_VERSION }}
          rebar3-version: ${{ env.CI_REBAR3_VERSION }}
      - name: Publish Hex package
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
        run: gleam publish -y
